### ISSUE TITLE
Add button to change language

### ISSUE THREAD

**Issue by jtagcat** [RaphaelJ/covid-tracer#10]
Many people have English as their phone language because the OS translation might be poor quality or they are used to English.

Maybe use GPS / Network Location / Cell provider for country-detection?

**Comment by RaphaelJ** [comment]
The application has been translated in a few languages (Portuguese, Spanish, Dutch, Crotian and French). As most mobile apps, it uses the language of the smartphone, but defaults to English if no translation is available for the chosen language.

I can add a new language provided you send me the translated `.resx` file: https://github.com/RaphaelJ/covid-tracer/blob/master/CovidTracer/Resx/Localization.resx

**Comment by RaphaelJ** [comment]
Ok, I just saw your Estonian translation. I'll add it to the next app build. Thank you.

**Comment by jtagcat** [comment]
By that I meant
Estonians usually have English as their phone language, because we are either used to English or their phone just doesn't offer Estonian.

**Comment by RaphaelJ** [comment]
Is it something Estonian user would expect from a mobile app? I went through apps I got on my phone, and only Waze was providing a way to select the language.

Why I can see the added value of having that setting in the app, I think it will require too much work for now (new setting screen and change of internationalization framework).

**Comment by jtagcat** [comment]
Well, maybe. As this is for everyone and the ~translation~ localization provides more detailed instructions for Estonia specifically, citing the government.

New setting screen doesn't sound like much work, it's just a menu listing items, what directly set a variable.

About the framework:
if (persistent_storage__localization_overridden_by_user == unset) {
lang_to_be_used = get device lang
} else {
lang_to_be_used = persistent_storage__user_locale
}

I'm actually a bit confused, why this is not using any libraries / thing you can pull in for translation. I get that you use the lang and tools what you already know, but for me this sounds like re-inventing the wheel.

**Comment by RaphaelJ** [comment]
It's already using localized .NET resources, which is the recommended way of handling localization in Xamarin and .NET apps. The library defaults to the system language, or to English if this one is not available. It's not that easy to change this behavior, especially not at runtime. 

It's not that the setting view would be that hard to design and implement, it's that as a personal, free and side project, I've got limited time to spend on it. There are more pressing features to be implemented as of today. If you don't agree with that, the app is a free software, you're free to contribute yourself, and that would be welcome.
