### ISSUE TITLE
Add build / developer instructions

### ISSUE THREAD

**Issue by jtagcat** [RaphaelJ/covid-tracer#12]
I don't know much about mobile apps nor c#.
I tried for an hour, gradle failed with `Task 'assemble' not found in root project 'covid-tracer'.`, omnisharp (vscode c# extension, attempted to get something out of the sln file) had many issues regarding dependencies in the extension's itself. Some issues I resolved, some I didn't.

Please add instructions on how to get from cloning the repo to an unsigned apk.

**Comment by RaphaelJ** [comment]
I don't think you'll be able to build the app using Gradle.

The app requires Visual Studio (not VSCode) as it has been created on top of Xamarin.

Normally, if you clone the repository, and open-it in Visual Studio (the `.csproj` file), you should be able to build the app for Android (and for iOS if you are on Mac OS and if you have a developer license).
