### ISSUE TITLE
Allow testing

### ISSUE THREAD

**Issue by tbarbette** [RaphaelJ/covid-tracer#16]
For the sakeness of trusting the app, it would be interesting to allow testing. Eg opt-in detection of neighboring smartphones with the app.

**Comment by RaphaelJ** [comment]
Hey Tom,

There is a hidden debug feature within the app. You can tap 10 times on the client key on the information screen.

Best

**Comment by jtagcat** [comment]
I'd add this fact to the readme after #7 is merged.

**Comment by RaphaelJ** [comment]
@jtagcat it's already mentioned at the end of the technical section of the README.
