### ISSUE TITLE
Spanish translation of Localization.resx

### ISSUE THREAD

**Issue by Barraguesh** [RaphaelJ/covid-tracer#2]
First things first, thanks for providing an alternative to the proprietary not privacy friendly apps that are being developed in this time of crisis. Hope that you're safe and stay like that until the situation returns somewhat to normality. Best of luck!
Also, I didn't see any recommended way of giving you the translated file so I hope this issue is ok with you.

    
    
    <data name="AboutTitle" xml:space="preserve">
        <value>Acerca de</value>
    </data>
    
    
    <data name="AboutTracerKey" xml:space="preserve">
        <value>ID CovidTracer</value>
    </data>
    
    <data name="AboutDetails" xml:space="preserve">
        <value>Este código único te identifica con otros usuarios de CovidTracer.</value>
    </data>
        
    <data name="AboutIcons" xml:space="preserve">
        <value>Iconos de Freepik en Flaticon.</value>
    </data>
    
    <data name="AboutFreeSoftware" xml:space="preserve">
        <value>CovidTracer es software gratuito y opensource.</value>
    </data>
    
    
    
    <data name="DetailsTitle" xml:space="preserve">
        <value>Detalles</value>
    </data>
    
    <data name="DetailsNoInteraction" xml:space="preserve">
        <value>No se ha detectado ninguna interacción de riesgo.</value>
    </data>
    
    
    <data name="DetailsInteractionPositiveTitle" xml:space="preserve">
        <value>Interacción con un positivo.</value>
    </data>
    
    
    <data name="DetailsInteractionPositiveDetails" xml:space="preserve">
        <value>Has estado en contacto cercano con uno o más casos positivos de coronavirus.</value>
    </data>
    
    
    <data name="DetailsInteractionSymptomaticTitle" xml:space="preserve">
        <value>Interaccion sospechosa.</value>
    </data>
    
    
    <data name="DetailsInteractionSymptomaticDetails" xml:space="preserve">
        <value>Has estado en contacto cercano con una o varias personas con síntomas parecidos a los del coronavirus.</value>
    </data>
    
    
    <data name="DetailsInteractionHistoryDate" xml:space="preserve">
        <value>{0} en {1}.</value>
    </data>
    
    
    
    <data name="MainTitle" xml:space="preserve">
        <value>CovidTracer</value>
    </data>
    
    <data name="MainAboutButton" xml:space="preserve">
        <value>Acerca de</value>
    </data>
    
    <data name="MainDetailsButton" xml:space="preserve">
        <value>Detalles</value>
    </data>
    
    <data name="MainSignalingButton" xml:space="preserve">
        <value>Reportar mi infección de coronavirus</value>
    </data>
    
    <data name="MainPrivacyDetails" xml:space="preserve">
        <value>CovidTracer respeta tu privacidad y no transmite datos personales por Internet. Respeta tanto como te sea posible la distancia de seguridad recomendada por tu gobierno local.</value>
    </data>
    
    <data name="MainStatusSafeTitle" xml:space="preserve">
        <value>Todo correcto</value>
    </data>
    
    <data name="MainStatusSafeText" xml:space="preserve">
        <value>No se ha detectado una interaccion con un caso positivo.</value>
    </data>
    
    <data name="MainStatusSymptomaticTitle" xml:space="preserve">
        <value>Riesgo moderado</value>
    </data>
    
    <data name="MainStatusSymptomaticText" xml:space="preserve">
        <value>Has estado en contacto con uno o varios casos sintomáticos a COVID-19.</value>
    </data>
    
    <data name="MainStatusPositiveTitle" xml:space="preserve">
        <value>High risk</value>
    </data>
    
    <data name="MainStatusPositiveText" xml:space="preserve">
        <value>YHas estado en contacto con uno o varios casos positivos de COVID-19.</value>
    </data>
    
    
    
    <data name="OnboardingContinue" xml:space="preserve">
        <value>Continuar</value>
    </data>
    
    <data name="OnboardingBluetooth" xml:space="preserve">
        <value>CovidTracer usa Bluetooth para notificarte anónimamente de cualquier contacto que hayas podido tener con personas infectadas con coronavirus.</value>
    </data>
    
    <data name="OnboardingPrivacy" xml:space="preserve">
        <value>CovidTracer es totalmente anónimo y no almacena tu información personal o localización. CovidTracer respeta tu privacidad.</value>
    </data>
    
    
    <data name="OnboardingRecommendedUses" xml:space="preserve">
        <value>Para una máxima eficacia, abre la app o déjala en segundo plano mientras interactúas con personas de fuera de tu casa (transportes, oficina, supermercados, actividades de exterior...).</value>
    </data>
    
    
    
    <data name="SignalingTitle" xml:space="preserve">
        <value>Reporte</value>
    </data>
    
    <data name="SignalingNotice" xml:space="preserve">
        <value>Al rellenar este formulario, los usuarios de CovidTracer con los que hayas podido interactuar durante tu periodo infeccioso serán notificados anónimamente.</value>
    </data>
    
    <data name="SignalingFormSymptomOnset" xml:space="preserve">
        <value>Inicio de los síntomas</value>
    </data>
    
    <data name="SignalingFormIsTested" xml:space="preserve">
        <value>He dado positivo en el test de SARS-CoV-2.</value>
    </data>
    
    <data name="SignalingFormComment" xml:space="preserve">
        <value>Comentario (opcional)</value>
    </data>
    
    <data name="SignalingFormSubmit" xml:space="preserve">
        <value>Enviar</value>
    </data>
    
    <data name="SignalingFormConfirmTitle" xml:space="preserve">
        <value>¿Continuar?</value>
    </data>
        
    <data name="SignalingFormConfirmText" xml:space="preserve">
        <value>Esta operación no podrá ser revertida.</value>
    </data>
        
    <data name="SignalingFormConfirmYes" xml:space="preserve">
        <value>Si</value>
    </data>
        
    <data name="SignalingFormConfirmNo" xml:space="preserve">
        <value>No</value>
    </data>
    
    
    <data name="SignalingSuccessTitle" xml:space="preserve">
        <value>Completado</value>
    </data>
    
    <data name="SignalingSuccessText" xml:space="preserve">
        <value>Tu infección ha sido notificada anónimamente.</value>
    </data>
    
    <data name="SignalingSuccessContinue" xml:space="preserve">
        <value>Continuar</value>
    </data>
    
    
    <data name="SignalingFailureTitle" xml:space="preserve">
        <value>Error</value>
    </data>
    
    <data name="SignalingFailureText" xml:space="preserve">
        <value>Operación fallida, por favor, inténtalo de nuevo más tarde.</value>
    </data>
    
    <data name="SignalingFailureContinue" xml:space="preserve">
        <value>Continuar</value>
    </data>
    
    <data name="SignalingAlreadyDoneText" xml:space="preserve">
        <value>Tu infección ha sido señalada con éxito.</value>
    </data>    
</root>

**Comment by RaphaelJ** [comment]
Thank you! I'll add it to the next release (v0.1.1).
